// <auto-generated />
using System;
using Greenmaster.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Greenmaster.Core.Migrations
{
    [DbContext(typeof(ArboretumContext))]
    [Migration("20230721101230_ChangedSignatureOfSpecieBloomPeriod")]
    partial class ChangedSignatureOfSpecieBloomPeriod
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GardenStyleMaterialType", b =>
                {
                    b.Property<int>("GardenStylesId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("integer");

                    b.HasKey("GardenStylesId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("GardenStyleMaterialType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Design.GardenStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllSeasonInterest")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("Concepts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DivideIntoRooms")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PathSize")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresLargeGarden")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Shapes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SuitablePlantGenera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GardenStyles");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Design.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Measurements.Dimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("objectType_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ObjectTypes");

                    b.HasDiscriminator<string>("objectType_type").HasValue("ObjectType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Placeable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DimensionsId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RenderingId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DimensionsId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RenderingId");

                    b.HasIndex("TypeId");

                    b.ToTable("Placeables");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Placeable");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.Property<double>("Z")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Rendering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Renderings");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttractsPollinators")
                        .HasColumnType("boolean");

                    b.Property<string>("BloomPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cultivar")
                        .HasColumnType("text");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlowerColors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFragrant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPoisonous")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxWidth")
                        .HasColumnType("double precision");

                    b.Property<int>("MinimalTemperature")
                        .HasColumnType("integer");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sunlight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Water")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Plant", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.Placeables.Placeable");

                    b.Property<int>("SpecieId")
                        .HasColumnType("integer");

                    b.HasIndex("SpecieId");

                    b.HasDiscriminator().HasValue("Plant");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Structure", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.Placeables.Placeable");

                    b.HasDiscriminator().HasValue("Structure");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.PlantType", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.ObjectType");

                    b.Property<bool>("AllowAsUndergrowth")
                        .HasColumnType("boolean");

                    b.Property<string>("Canopy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("PlantType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.StructureType", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.ObjectType");

                    b.HasDiscriminator().HasValue("StructureType");
                });

            modelBuilder.Entity("GardenStyleMaterialType", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Design.GardenStyle", null)
                        .WithMany()
                        .HasForeignKey("GardenStylesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.Design.MaterialType", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Placeable", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Measurements.Dimensions", "Dimensions")
                        .WithMany()
                        .HasForeignKey("DimensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.Point", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Greenmaster.Core.Models.Rendering", "Rendering")
                        .WithMany()
                        .HasForeignKey("RenderingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.ObjectType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensions");

                    b.Navigation("Location");

                    b.Navigation("Rendering");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Specie", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.PlantType", "PlantType")
                        .WithMany()
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Plant", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Specie", "Specie")
                        .WithMany()
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specie");
                });
#pragma warning restore 612, 618
        }
    }
}
