// <auto-generated />
using System;
using Greenmaster.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Greenmaster.Core.Migrations
{
    [DbContext(typeof(ArboretumContext))]
    [Migration("20240926192128_AddedStaticDataSeeding")]
    partial class AddedStaticDataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GardenStyleMaterialType", b =>
                {
                    b.Property<int>("GardenStylesId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("int");

                    b.HasKey("GardenStylesId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("GardenStyleMaterialType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Design.GardenStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllSeasonInterest")
                        .HasColumnType("bit");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concepts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DivideIntoRooms")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PathSize")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresLargeGarden")
                        .HasColumnType("bit");

                    b.Property<string>("Shapes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuitablePlantGenera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GardenStyles");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Design.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wood",
                            Name = "Wood"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Stone",
                            Name = "Stone"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brick",
                            Name = "Brick"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Corten steel, is a group of steel alloys which were developed to eliminate the need for painting, and form a stable rust-like appearance.",
                            Name = "Corten steel"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A gabion is a cage, cylinder or box filled with rocks, concrete, or sometimes sand and soil.",
                            Name = "Gabion"
                        });
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Measurements.Dimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("objectType_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjectTypes");

                    b.HasDiscriminator<string>("objectType_type").HasValue("ObjectType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Placeable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DimensionsId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RenderingId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("placeable_filler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionsId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RenderingId");

                    b.HasIndex("TypeId");

                    b.ToTable("Placeables");

                    b.HasDiscriminator<string>("placeable_filler").HasValue("Placeable");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Rendering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Renderings");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BloomPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cultivar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowerColors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFragrant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPoisonous")
                        .HasColumnType("bit");

                    b.Property<double>("MaxHeight")
                        .HasColumnType("float");

                    b.Property<double>("MaxWidth")
                        .HasColumnType("float");

                    b.Property<int>("MinimalTemperature")
                        .HasColumnType("int");

                    b.Property<string>("MutualisticGenera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("PollinatingFlowers")
                        .HasColumnType("bit");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sunlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Water")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Plant", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.Placeables.Placeable");

                    b.Property<int>("SpecieId")
                        .HasColumnType("int");

                    b.HasIndex("SpecieId");

                    b.HasDiscriminator().HasValue("Plant");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Structure", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.Placeables.Placeable");

                    b.HasDiscriminator().HasValue("Structure");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.PlantType", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.ObjectType");

                    b.Property<bool>("AllowAsUndergrowth")
                        .HasColumnType("bit");

                    b.Property<string>("Canopy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PlantType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hedges are rows of closely planted shrubs, and come in all shapes, styles and sizes.",
                            Name = "Hedge",
                            AllowAsUndergrowth = false,
                            Canopy = "Closed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trees have a permanent woody structure – usually a single trunk and a network of branches. Some grow quite large, but there are plenty of smaller options too. Most offer an array of attractive features, including decorative foliage, flowers, fruits and bark. Some keep their leaves all year, while others are leafless over winter.",
                            Name = "Tree",
                            AllowAsUndergrowth = false,
                            Canopy = "Closed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "These plants clothe walls and supports in foliage and flowers. Climbers cling on using tendrils, twining stems, stem roots or sticky pads, while wall shrubs need to be tied to supports. Plants can be large and vigorous or neat and compact, some are evergreen retaining their foliage all year, while others are deciduous and lose their leaves over winter. ",
                            Name = "Climber",
                            AllowAsUndergrowth = true,
                            Canopy = "Partial"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Small shrubs have a permanent structure of woody stems. They come in all shapes, some holding onto their leaves all year, others losing them in autumn. As well as flowers in every possible hue, many shrubs have attractive foliage and fruits.",
                            Name = "Small shrub (<2 metres)",
                            AllowAsUndergrowth = true,
                            Canopy = "Partial"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Large shrubs have a permanent structure of woody stems. They come in all shapes, some holding onto their leaves all year, others losing them in autumn. As well as flowers in every possible hue, many shrubs have attractive foliage, fruits and bark.",
                            Name = "Large shrub (2-8 metres)",
                            AllowAsUndergrowth = true,
                            Canopy = "Partial"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Versatile, hardy and spectacular, bringing movement, texture and drama to gardens of all styles, nearly all year round.",
                            Name = "Grass",
                            AllowAsUndergrowth = true,
                            Canopy = "NotSet"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ferns can be large or small, often with elegantly arching, feathery foliage. The plants usually have a shuttlecock shape, with new growth unfurling from the centre. Deciduous types die down in winter, while evergreen and semi-evergreen have a year-round presence.",
                            Name = "Fern",
                            AllowAsUndergrowth = true,
                            Canopy = "Closed"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Aquatic and bog plants tend to be big and bold, lush and leafy, with brightly coloured flowers. Some aquatics spread out across the pond’s surface, while others grow vertically out of the water.",
                            Name = "Aquatic",
                            AllowAsUndergrowth = true,
                            Canopy = "Partial"
                        },
                        new
                        {
                            Id = 9,
                            Description = "It includes a wide range of flower shapes, colours and sizes as this is a large and diverse group.",
                            Name = "Bulb",
                            AllowAsUndergrowth = true,
                            Canopy = "Partial"
                        },
                        new
                        {
                            Id = 10,
                            Description = "They come in a huge range of shapes, colours and forms, some covered in spines, others smooth or furry, some gently rounded, others angular and sculptural.",
                            Name = "Succulent",
                            AllowAsUndergrowth = false,
                            Canopy = "NotSet"
                        },
                        new
                        {
                            Id = 11,
                            Description = "They come in a huge range of shapes, colours and forms, some covered in spines, others smooth or furry, some gently rounded, others angular and sculptural.",
                            Name = "Cactus",
                            AllowAsUndergrowth = false,
                            Canopy = "Open"
                        });
                });

            modelBuilder.Entity("Greenmaster.Core.Models.StructureType", b =>
                {
                    b.HasBaseType("Greenmaster.Core.Models.ObjectType");

                    b.HasDiscriminator().HasValue("StructureType");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "/",
                            Name = "Swimming pool"
                        },
                        new
                        {
                            Id = 101,
                            Description = "/",
                            Name = "Pond"
                        },
                        new
                        {
                            Id = 102,
                            Description = "/",
                            Name = "Garage"
                        },
                        new
                        {
                            Id = 103,
                            Description = "/",
                            Name = "Swing"
                        },
                        new
                        {
                            Id = 104,
                            Description = "/",
                            Name = "Animal pen"
                        },
                        new
                        {
                            Id = 105,
                            Description = "/",
                            Name = "Shed"
                        });
                });

            modelBuilder.Entity("GardenStyleMaterialType", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Design.GardenStyle", null)
                        .WithMany()
                        .HasForeignKey("GardenStylesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.Design.MaterialType", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Placeable", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Measurements.Dimensions", "Dimensions")
                        .WithMany()
                        .HasForeignKey("DimensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.Point", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Greenmaster.Core.Models.Rendering", "Rendering")
                        .WithMany()
                        .HasForeignKey("RenderingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenmaster.Core.Models.ObjectType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensions");

                    b.Navigation("Location");

                    b.Navigation("Rendering");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Specie", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.PlantType", "PlantType")
                        .WithMany()
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Placeables.Plant", b =>
                {
                    b.HasOne("Greenmaster.Core.Models.Specie", "Specie")
                        .WithMany("Plants")
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Greenmaster.Core.Models.Specie", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
